#######################################################################
#                                                                     #
#         Array Practice Core - Developed By Drizzy#0278              #
#     Bought at Purge Development - https://discord.gg/VXzUMfBefZ     #
#                                                                     #
#######################################################################
LICENSE: ""
MONGO:
  URI-MODE: true
  NORMAL:
    HOST: 127.0.0.1
    PORT: '27017'
    DATABASE: Array
    AUTHENTICATION:
      ENABLED: false
      USERNMAE: ''
      PASSWORD: ''
  URI:
    DATABASE: Array
    CONNECTION_STRING: mongodb://127.0.0.1:27017/Array
ESSENTIAL:
  SPAWN: practice:0.5:69.0:-0.5:0.0:0.0
  CORE_HOOK: true
  HCF_ENABLED: true
  TAB_ENABLED: true
  VOIDSPAWN_YLEVEL: 45
  BRIDGE_CLEARBLOCKS: true
  FFA_CIRCLE_RADIUS: 10
  REMOVE_BOTTLES: true
  JOIN_MESSAGE_ENABLED: true
  DISCLAIMER_MESSAGE_ENABLED: true
  JOIN_MESSAGE:
    - ""
    - "&c&lArray &7&l| &fPractice &7(EU)"
    - "&7Welcome to the &cTest Server &7of &cArray Practice&7."
    - ""
    - "&7Purchase Array at &chttps://discord.gg/BpZEnwsQgY&7."
    - "&7Engage with our community at &cdiscord.link/purge&7."
    - ""
SOCIAL:
  DISCORD: discord.link/purge
  STORE: store.purgecommunity.com
  WEBSITE: www.purgecommunity.com
  TWITTER: '@PurgeCommunity'
RANKED:
  ENABLED: true
  REQUIREKILLS: true
  REQUIREDKILLS: 10
  LIMIT_PING: true
  PING-LIMIT: 0
NAMETAGS:
  ENABLED: true
  DEFAULT: <rank_color>
  PARTY: BLUE
  EVENT: AQUA
QUEUE_LORE:
  - "&7&m----------------------"
  - "&7In Queue: &c{in_queue}"
  - "&7In Fight: &c{in_fight}"
  - ""
  - "&7Click to join queue."
  - "&7&m----------------------"